####  application-dev.yml
server:
  port: 8002

logging:
  pattern:
    console: "%clr(%5p) %clr(-){faint} %clr(%-80.80logger{79}){cyan} %clr(:) %m%n"

spring:
  application:
    name: service-upload
  profiles:
    include: dev,oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80 #nacos服务的地址 不要加http

